# -------- Tracking Setting for Sequence ETH-Crossing --------
ID_assign_init                      : 30
ID_birth_init                       : -10
DeathBufferLength                   : 2000
BirthBufferLength                   : 5000
DeathCount                          : 8
BirthCount                          : 1
Threshold                           : -3
Distance                            : 0.075
BoxRation                           : 0.3
FrameWidth                          : 640
FrameHeight                         : 480
fps                                 : 14
PredictThreshold                    : 0.0075
# ------------------------------------------------------------