# ------------- Tracking Setting for Sequence 06 -------------
ID_assign_init                      : 20
ID_birth_init                       : -10
DeathBufferLength                   : 2000
BirthBufferLength                   : 5000
DeathCount                          : 6
BirthCount                          : 3
Threshold                           : -3
Distance                            : 0.06
BoxRation                           : 0.3
FrameWidth                          : 640
FrameHeight                         : 480
fps                                 : 7
PredictThreshold                    : 0.006
# ------------------------------------------------------------